In [51]:
#mlpformulticlassclassification
from numpy import argmax 
from pandas import read_csv 
from sklearn.model_selection import train_test_split
from sklearn.preprocessing import LabelEncoder 
from tensorflow.keras import Sequential
from tensorflow.keras.layers import Dense
import tensorflow as tf
import numpy as np

# multiclass classification

In [2]:
#load the dataset
path='https://raw.githubusercontent.com/jbrownlee/Datasets/master/iris.csv'
df=read_csv(path,header=None)

In [3]:
df

0    1    2    3               4
0    5.1  3.5  1.4  0.2     Iris-setosa
1    4.9  3.0  1.4  0.2     Iris-setosa
2    4.7  3.2  1.3  0.2     Iris-setosa
3    4.6  3.1  1.5  0.2     Iris-setosa
4    5.0  3.6  1.4  0.2     Iris-setosa
..   ...  ...  ...  ...             ...
145  6.7  3.0  5.2  2.3  Iris-virginica
146  6.3  2.5  5.0  1.9  Iris-virginica
147  6.5  3.0  5.2  2.0  Iris-virginica
148  6.2  3.4  5.4  2.3  Iris-virginica
149  5.9  3.0  5.1  1.8  Iris-virginica

[150 rows x 5 columns]

In [18]:
df[4].unique()

array(['Iris-setosa', 'Iris-versicolor', 'Iris-virginica'], dtype=object)

In [4]:
df.values

array([[5.1, 3.5, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.0, 1.4, 0.2, 'Iris-setosa'],
       [4.7, 3.2, 1.3, 0.2, 'Iris-setosa'],
       [4.6, 3.1, 1.5, 0.2, 'Iris-setosa'],
       [5.0, 3.6, 1.4, 0.2, 'Iris-setosa'],
       [5.4, 3.9, 1.7, 0.4, 'Iris-setosa'],
       [4.6, 3.4, 1.4, 0.3, 'Iris-setosa'],
       [5.0, 3.4, 1.5, 0.2, 'Iris-setosa'],
       [4.4, 2.9, 1.4, 0.2, 'Iris-setosa'],
       [4.9, 3.1, 1.5, 0.1, 'Iris-setosa'],
       [5.4, 3.7, 1.5, 0.2, 'Iris-setosa'],
       [4.8, 3.4, 1.6, 0.2, 'Iris-setosa'],
       [4.8, 3.0, 1.4, 0.1, 'Iris-setosa'],
       [4.3, 3.0, 1.1, 0.1, 'Iris-setosa'],
       [5.8, 4.0, 1.2, 0.2, 'Iris-setosa'],
       [5.7, 4.4, 1.5, 0.4, 'Iris-setosa'],
       [5.4, 3.9, 1.3, 0.4, 'Iris-setosa'],
       [5.1, 3.5, 1.4, 0.3, 'Iris-setosa'],
       [5.7, 3.8, 1.7, 0.3, 'Iris-setosa'],
       [5.1, 3.8, 1.5, 0.3, 'Iris-setosa'],
       [5.4, 3.4, 1.7, 0.2, 'Iris-setosa'],
       [5.1, 3.7, 1.5, 0.4, 'Iris-setosa'],
       [4.6, 3.6, 1.0, 0.2, 'Iri

In [5]:
#split into input and output columns 
X,y=df.values[:,:-1],df.values[:,-1]

In [7]:
X.shape,y.shape

((150, 4), (150,))

In [22]:
#ensure all data are floating point values 
X=X.astype('float32')

In [23]:
#encode strings to integer 
y=LabelEncoder().fit_transform(y)

In [24]:
y

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0, 0,
       0, 0, 0, 0, 0, 0, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1,
       1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 1, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2,
       2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2, 2])

In [25]:
#split into train and test data sets
x_train,x_test,y_train,y_test = train_test_split(X,y,test_size=0.33)

In [28]:
x_train.shape,y_train.shape

((100, 4), (100,))

In [29]:
x_test.shape,y_test.shape

((50, 4), (50,))

In [30]:
# define the model 
n_dimension = x_test.shape[1]
model = Sequential([
    Dense(10,activation='relu',input_shape=((n_dimension,))),
    Dense(8,activation='relu'),
    Dense(3,activation='softmax')
])

In [41]:
model.compile(optimizer = tf.keras.optimizers.Adam() , loss="sparse_categorical_crossentropy")

In [46]:
model.fit(x_train,y_train,epochs=500)

Epoch 1/500
4/4 [==============================] - 0s 6ms/step - loss: 0.0790
Epoch 2/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0783
Epoch 3/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0786
Epoch 4/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0783
Epoch 5/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0781
Epoch 6/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0777
Epoch 7/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0778
Epoch 8/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0777
Epoch 9/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0777
Epoch 10/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0775
Epoch 11/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0768
Epoch 12/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0781
Epoch 13/500
4/4 [==============================] - 0s 4ms/st

4/4 [==============================] - 0s 5ms/step - loss: 0.0719
Epoch 105/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0715
Epoch 106/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0716
Epoch 107/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0709
Epoch 108/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0710
Epoch 109/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0706
Epoch 110/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0715
Epoch 111/500
4/4 [==============================] - 0s 6ms/step - loss: 0.0709
Epoch 112/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0737
Epoch 113/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0746
Epoch 114/500
4/4 [==============================] - 0s 6ms/step - loss: 0.0738
Epoch 115/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0705
Epoch 116/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 5ms/step - loss: 0.0666
Epoch 207/500
4/4 [==============================] - 0s 6ms/step - loss: 0.0696
Epoch 208/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0696
Epoch 209/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0671
Epoch 210/500
4/4 [==============================] - 0s 6ms/step - loss: 0.0663
Epoch 211/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0663
Epoch 212/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0661
Epoch 213/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0675
Epoch 214/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0679
Epoch 215/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0673
Epoch 216/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0673
Epoch 217/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0666
Epoch 218/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 5ms/step - loss: 0.0634
Epoch 309/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0647
Epoch 310/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0648
Epoch 311/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0640
Epoch 312/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0639
Epoch 313/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0635
Epoch 314/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0634
Epoch 315/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0633
Epoch 316/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0666
Epoch 317/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0712
Epoch 318/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0699
Epoch 319/500
4/4 [==============================] - 0s 4ms/step - loss: 0.0667
Epoch 320/500
4/4 [==============================] - 0

4/4 [==============================] - 0s 5ms/step - loss: 0.0613
Epoch 411/500
4/4 [==============================] - 0s 6ms/step - loss: 0.0617
Epoch 412/500
4/4 [==============================] - 0s 6ms/step - loss: 0.0618
Epoch 413/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0616
Epoch 414/500
4/4 [==============================] - 0s 6ms/step - loss: 0.0614
Epoch 415/500
4/4 [==============================] - 0s 7ms/step - loss: 0.0614
Epoch 416/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0613
Epoch 417/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0621
Epoch 418/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0618
Epoch 419/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0614
Epoch 420/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0612
Epoch 421/500
4/4 [==============================] - 0s 5ms/step - loss: 0.0611
Epoch 422/500
4/4 [==============================] - 0

## evaluate the model

In [47]:
y_prid = model.predict(x_test)

2/2 [==============================] - 0s 16ms/step


In [57]:
y_prid.shape

(50, 3)

In [62]:
y_prid = np.argmax(y_prid,axis=1)

In [65]:
y_prid = y_prid.astype('int32')

In [67]:
y_prid,y_test

(array([0, 0, 2, 2, 2, 1, 2, 1, 0, 2, 0, 1, 1, 2, 0, 1, 1, 2, 1, 0, 2, 1,
        2, 2, 0, 0, 0, 1, 2, 0, 2, 0, 1, 0, 1, 2, 2, 2, 2, 0, 0, 1, 2, 2,
        0, 2, 1, 2, 1, 0]),
 array([0, 0, 2, 2, 2, 1, 2, 1, 0, 2, 0, 1, 1, 2, 0, 1, 1, 2, 1, 0, 2, 1,
        2, 2, 0, 0, 0, 1, 2, 0, 2, 0, 2, 0, 1, 2, 2, 2, 2, 0, 0, 1, 2, 2,
        0, 2, 1, 2, 1, 0]))

In [73]:
(y_prid == y_test)

array([ True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True, False,  True,  True,  True,
        True,  True,  True,  True,  True,  True,  True,  True,  True,
        True,  True,  True,  True,  True])

In [79]:
np.where(y_prid != y_test)[0][0]

32

In [81]:
y_prid[32],y_test[32]

(1, 2)

In [70]:
(y_prid == y_test).sum() / len(y_test)

0.98

In [71]:
model.evaluate(x_test,y_test)

2/2 [==============================] - 0s 21ms/step - loss: 0.0743


0.0743272677063942

# regression model

In [84]:
# load the dataset 
path='https://raw.githubusercontent.com/jbrownlee/Datasets/master/housing.csv'
df=read_csv(path,header=None)

In [126]:
df

0     1      2   3      4      5     6       7   8      9     10  \
0    0.00632  18.0   2.31   0  0.538  6.575  65.2  4.0900   1  296.0  15.3   
1    0.02731   0.0   7.07   0  0.469  6.421  78.9  4.9671   2  242.0  17.8   
2    0.02729   0.0   7.07   0  0.469  7.185  61.1  4.9671   2  242.0  17.8   
3    0.03237   0.0   2.18   0  0.458  6.998  45.8  6.0622   3  222.0  18.7   
4    0.06905   0.0   2.18   0  0.458  7.147  54.2  6.0622   3  222.0  18.7   
..       ...   ...    ...  ..    ...    ...   ...     ...  ..    ...   ...   
501  0.06263   0.0  11.93   0  0.573  6.593  69.1  2.4786   1  273.0  21.0   
502  0.04527   0.0  11.93   0  0.573  6.120  76.7  2.2875   1  273.0  21.0   
503  0.06076   0.0  11.93   0  0.573  6.976  91.0  2.1675   1  273.0  21.0   
504  0.10959   0.0  11.93   0  0.573  6.794  89.3  2.3889   1  273.0  21.0   
505  0.04741   0.0  11.93   0  0.573  6.030  80.8  2.5050   1  273.0  21.0   

         11    12    13  
0    396.90  4.98  24.0  
1    396.90  9.14  21.6  
2    392.83  4.03  34.7  
3    394.63  2.94  33.4  
4    396.90  5.33  36.2  
..      ...   ...   ...  
501  391.99  9.67  22.4  
502  396.90  9.08  20.6  
503  396.90  5.64  23.9  
504  393.45  6.48  22.0  
505  396.90  7.88  11.9  

[506 rows x 14 columns]

In [127]:
# split the inputs and the label 
x = df.values[:,:-1]; y = df.values[:,-1]

In [128]:
x.shape,y.shape

((506, 13), (506,))

In [129]:
X_train, X_test, y_train, y_test = train_test_split(x,y,test_size=0.2)

In [130]:
X_train.shape,y_train.shape

((404, 13), (404,))

In [131]:
X_test.shape,y_test.shape

((102, 13), (102,))

## define the model 

In [138]:
model = Sequential([
    Dense(30,activation = 'relu'),
    Dense(20,activation = 'relu'),
    Dense(8,activation = 'relu'),
    Dense(1,activation = 'linear')
])

In [139]:
model.compile(optimizer=tf.optimizers.Adam(learning_rate=0.001),loss='mse')

In [140]:
model.fit(X_train,y_train,epochs=300)

Epoch 1/300
13/13 [==============================] - 1s 4ms/step - loss: 1011.5055
Epoch 2/300
13/13 [==============================] - 0s 4ms/step - loss: 226.3776
Epoch 3/300
13/13 [==============================] - 0s 3ms/step - loss: 97.4418
Epoch 4/300
13/13 [==============================] - 0s 4ms/step - loss: 88.4176
Epoch 5/300
13/13 [==============================] - 0s 4ms/step - loss: 77.3767
Epoch 6/300
13/13 [==============================] - 0s 4ms/step - loss: 76.2401
Epoch 7/300
13/13 [==============================] - 0s 3ms/step - loss: 76.4910
Epoch 8/300
13/13 [==============================] - 0s 4ms/step - loss: 74.1725
Epoch 9/300
13/13 [==============================] - 0s 3ms/step - loss: 74.0183
Epoch 10/300
13/13 [==============================] - 0s 3ms/step - loss: 73.2959
Epoch 11/300
13/13 [==============================] - 0s 3ms/step - loss: 72.4737
Epoch 12/300
13/13 [==============================] - 0s 3ms/step - loss: 72.0240
Epoch 13/300
13/13 [==

Epoch 101/300
13/13 [==============================] - 0s 3ms/step - loss: 24.0711
Epoch 102/300
13/13 [==============================] - 0s 3ms/step - loss: 24.9854
Epoch 103/300
13/13 [==============================] - 0s 3ms/step - loss: 24.8375
Epoch 104/300
13/13 [==============================] - 0s 4ms/step - loss: 25.6255
Epoch 105/300
13/13 [==============================] - 0s 3ms/step - loss: 24.0537
Epoch 106/300
13/13 [==============================] - 0s 3ms/step - loss: 24.4957
Epoch 107/300
13/13 [==============================] - 0s 3ms/step - loss: 23.2134
Epoch 108/300
13/13 [==============================] - 0s 3ms/step - loss: 23.5449
Epoch 109/300
13/13 [==============================] - 0s 3ms/step - loss: 24.0389
Epoch 110/300
13/13 [==============================] - 0s 3ms/step - loss: 23.5544
Epoch 111/300
13/13 [==============================] - 0s 3ms/step - loss: 23.5499
Epoch 112/300
13/13 [==============================] - 0s 4ms/step - loss: 24.5845
Epoc

13/13 [==============================] - 0s 4ms/step - loss: 16.1180
Epoch 200/300
13/13 [==============================] - 0s 5ms/step - loss: 17.5096
Epoch 201/300
13/13 [==============================] - 0s 4ms/step - loss: 19.8323
Epoch 202/300
13/13 [==============================] - 0s 4ms/step - loss: 21.7880
Epoch 203/300
13/13 [==============================] - 0s 4ms/step - loss: 19.1143
Epoch 204/300
13/13 [==============================] - 0s 3ms/step - loss: 16.5955
Epoch 205/300
13/13 [==============================] - 0s 4ms/step - loss: 15.5675
Epoch 206/300
13/13 [==============================] - 0s 4ms/step - loss: 15.4959
Epoch 207/300
13/13 [==============================] - 0s 4ms/step - loss: 18.9653
Epoch 208/300
13/13 [==============================] - 0s 4ms/step - loss: 19.8992
Epoch 209/300
13/13 [==============================] - 0s 4ms/step - loss: 16.4262
Epoch 210/300
13/13 [==============================] - 0s 4ms/step - loss: 17.3686
Epoch 211/300
13/1

13/13 [==============================] - 0s 4ms/step - loss: 14.7960
Epoch 298/300
13/13 [==============================] - 0s 4ms/step - loss: 15.5676
Epoch 299/300
13/13 [==============================] - 0s 4ms/step - loss: 16.0563
Epoch 300/300
13/13 [==============================] - 0s 4ms/step - loss: 15.2544


In [141]:
error = model.evaluate(X_test,y_test)

4/4 [==============================] - 0s 7ms/step - loss: 14.1887


In [117]:
print(f"MSE = {error}, RMSE = {np.sqrt(error)}")

MSE = 21.4457950592041, RMSE = 4.630960489920433


In [142]:
y_prid = model.predict(X_test)
y_prid

4/4 [==============================] - 0s 4ms/step


array([[19.499022 ],
       [16.95098  ],
       [30.983324 ],
       [34.024357 ],
       [22.340551 ],
       [19.206526 ],
       [19.957949 ],
       [22.04791  ],
       [12.540487 ],
       [ 9.307997 ],
       [19.470434 ],
       [13.90621  ],
       [24.428186 ],
       [38.09235  ],
       [30.916689 ],
       [ 7.212744 ],
       [ 8.099356 ],
       [32.97001  ],
       [14.288336 ],
       [36.475975 ],
       [18.572897 ],
       [23.711088 ],
       [20.95709  ],
       [25.574629 ],
       [ 9.006865 ],
       [22.25302  ],
       [11.053732 ],
       [21.148123 ],
       [22.497324 ],
       [33.896587 ],
       [25.183336 ],
       [10.275862 ],
       [ 9.575773 ],
       [15.227133 ],
       [21.824804 ],
       [15.275114 ],
       [ 9.209898 ],
       [ 9.540693 ],
       [22.214682 ],
       [20.258013 ],
       [25.201971 ],
       [20.480505 ],
       [45.817093 ],
       [20.807753 ],
       [15.008879 ],
       [23.804075 ],
       [20.590548 ],
       [21.59

In [143]:
y_test

array([21.5, 17.4, 32.9, 27. , 28.7, 21.7, 13.1, 26.5, 15.1, 13.8, 19.8,
       16.3, 24.7, 50. , 37.3, 13.1, 13.8, 35.4, 11.8, 41.3, 15.6, 20.7,
       22.9, 29.1, 10.2, 21.4, 13.9, 24.5, 27.1, 42.3, 22.2,  6.3, 10.2,
       17.2, 22. , 21.4, 10.2, 10.4, 22.9, 24.3, 28. , 18.2, 50. , 20.6,
        8.7, 23.2, 18.8, 16.8, 13.3, 20.1, 23.2, 19.4, 32.7, 31.7,  7.5,
       28.2, 25. , 20.2, 17.2, 21.7, 13.8, 23.6, 21.7, 18.9, 24.1, 20.5,
       23.1, 14.9, 20.8, 36.4, 19.8, 21. , 17.8, 16.5, 25. , 13.4, 13.4,
       23.7, 22.5, 23.1, 25. , 16.5, 23. , 22. , 33.2, 13.4,  7.2, 22.3,
       14.1, 15.4, 11. , 12.7, 24.7, 21.1, 17.1, 37.6, 12.5, 14.1, 23.9,
       17. , 26.2, 27.5])

In [144]:
abs(y_prid - y_test).mean()

8.73873658711889

## notes 
- the performance of the model got better when we made the NN slightly larger 
- the performance also got better when we used more examples (increased the size of the training data to 80% )